### ISSUE TITLE
Authentication Fails with "Bad username or password"

### ISSUE THREAD

**Issue by 54** [Delthas/JavaSkype#23]
I just tried the sample code on the read me file and was treated with an authentication failure. I went ahead and tried both the latest version of the library from the master branch and version 1.0.15.

I am logging in with an email / Microsoft account if that makes any difference.

Here is my debug log: https://gist.github.com/54/06dd32b6ceaff8ec1060a45636c3293f

**Comment by Delthas** [comment]
Yes this does make a difference, because this library only works for users that are not using Microsoft accounts. Sorry. I should add it to the description.

Only Skype-only accounts can connect because the way Microsoft-only accounts work/connect to the Skype servers is vastly different the Skype-only accounts. I don't plan on adding support for Microsoft accounts in the near future, but I'll add an issue for this anyway.
